### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anler**
Hi! Thanks a lot for this package ❤️ . I added instructions of how to use it with use-package since that's what I use to configure my [.emacs.d](http://github.com/anler/.emacs.d).

### CODE REVIEW

**Comment by marsam** [comment]
Thanks, the readme is autogenerated, would you mind moving your changes to the `Commentary:` section in `markdown-edit-indirect.el` and call `make README.md`

**Comment by anler** [comment]
@marsam is that the new commit correct?

**Comment by marsam** [comment]
yes, thanks!

**Comment by anler** [comment]
thank you!

**Pull request merged**
